import { useSyncExternalStore } from 'react';
import { media, playback, store, transcripts } from '../app/editor';
import { toastStore } from '../app/notify';
import { analysisStore } from '../app/analysis';
import { smartCutStore } from '../app/smartCut';
import { viewStore } from '../app/view';
import { phaseRunStore } from '../app/phases';
import { aiStore } from '../app/aiEditor';
import { prefsStore } from '../app/prefs';

export const useEditor = () => useSyncExternalStore(store.subscribe, store.getState);
export const usePlayback = () => useSyncExternalStore(playback.subscribe, playback.getSnapshot);
export const useMediaVersion = () => useSyncExternalStore(media.subscribe, media.getVersion);
export const useTranscriptsVersion = () => useSyncExternalStore(transcripts.subscribe, transcripts.getVersion);
export const useAnalysis = () => useSyncExternalStore(analysisStore.subscribe, analysisStore.get);
export const usePhaseRun = () => useSyncExternalStore(phaseRunStore.subscribe, phaseRunStore.get);
export const useView = () => useSyncExternalStore(viewStore.subscribe, viewStore.get);
export const useSmartCut = () => useSyncExternalStore(smartCutStore.subscribe, smartCutStore.get);
export const useToasts = () => useSyncExternalStore(toastStore.subscribe, toastStore.get);
export const useAI = () => useSyncExternalStore(aiStore.subscribe, aiStore.get);
export const usePrefs = () => useSyncExternalStore(prefsStore.subscribe, prefsStore.get);
