name: Build and Release FOCO Editor

on:
  push:
    tags:
      - 'v*.*.*' # Roda quando sobe uma tag de versÃ£o, ex: v1.0.1
  workflow_dispatch: {}

permissions:
  contents: write # necessÃ¡rio para criar o Release com o instalador

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checar o cÃ³digo (Checkout)
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar DependÃªncias
        run: npm install

      - name: Build do Electron e PublicaÃ§Ã£o no GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win --publish always
